_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 80
                - 105
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 80
                - 105
            "3":
                - 2
                - 13
                - 16
                - 55
            "4": 3.11.13
            "5": 0.20.1
            "8":
                - 1
                - 2
                - 12
            "12": 0.20.1
            "13": linux-x86_64
batch_size:
    value: 32
data_dir:
    value: /kaggle/input/the-iqothnccd-lung-cancer-dataset/The IQ-OTHNCCD lung cancer dataset
device:
    value: cuda
dropout:
    value: 0.5
epochs:
    value: 50
key_dim:
    value: 16
learning_rate:
    value: 1e-05
num_heads:
    value: 4
