_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 55
                - 105
            "2":
                - 1
                - 55
                - 105
            "3":
                - 2
                - 3
                - 16
                - 23
                - 55
                - 62
            "4": 3.10.12
            "5": 0.19.1
            "8":
                - 1
                - 2
                - 5
                - 12
            "12": 0.19.1
            "13": linux-x86_64
batch_size:
    value: 16
block_size:
    value: 32
dropout:
    value: 0.2
eval_interval:
    value: 500
eval_iters:
    value: 200
learning_rate:
    value: 0.001
max_iters:
    value: 5000
n_embd:
    value: 32
n_head:
    value: 2
n_layer:
    value: 2
