_wandb:
    value:
        cli_version: 0.25.0
        e:
            4amvwaazb9n7hcajiq0etssyv3yeoeig:
                codePath: kaggle.ipynb
                cpu_count: 112
                cpu_count_logical: 224
                disk:
                    /:
                        total: "8656922775552"
                        used: "7169057058816"
                email: <redacted>
                executable: /usr/local/bin/python
                host: ddff5d159392
                memory:
                    total: "405703245824"
                os: Linux-6.1.42+-x86_64-with-glibc2.41
                program: kaggle.ipynb
                python: CPython 3.12.12
                root: /kaggle/working
                startedAt: "2026-03-01T19:58:19.824457Z"
                tpu:
                    count: 8
                    devicesPerChip: 1
                    hbmGib: 16
                    name: v5e
                writerId: 4amvwaazb9n7hcajiq0etssyv3yeoeig
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 12
                - 45
                - 49
                - 53
                - 80
            "2":
                - 1
                - 2
                - 3
                - 5
                - 12
                - 45
                - 49
                - 53
                - 80
            "3":
                - 2
                - 13
                - 16
            "4": 3.12.12
            "5": 0.25.0
            "8":
                - 1
                - 2
            "12": 0.25.0
            "13": linux-x86_64
accelerator:
    value: TPU v5e × 8
base_channels:
    value: 128
effective_batch:
    value: 24
epochs:
    value: 3000
framework:
    value: JAX/Flax
img_size:
    value: 224
lr:
    value: 0.00015
lr_schedule:
    value: cosine_decay
method:
    value: Rectified Flow
params:
    value: 73459585
per_device_batch:
    value: 3
profile_enabled:
    value: true
profile_every_epochs:
    value: 20
