#!/usr/bin/env python3
"""Regenerate the showcase from the Weights & Biases export in ../prev_experiments.

Everything under projects/*/{README.md,runs.csv,figures/} is generated by this
script and can be deleted and rebuilt at any time.  Directories that Gemini
fills in (code/, weights/) are never touched.

    python3 tools/build.py
"""
import csv, json, re, shutil, sys
from pathlib import Path

csv.field_size_limit(10**9)

ROOT = Path(__file__).resolve().parent.parent
EXPORT = ROOT.parent / "prev_experiments"
PROJECTS = ROOT / "projects"

# Figures worth showing a reviewer: evaluation plots, not generator sample grids.
EVAL = re.compile(r"confusion|roc|curve|gradcam|attention|matrix|results|f1|precision|recall",
                  re.I)
MAX_RUNS_WITH_FIGURES = 10   # per project
MAX_SAMPLE_GRIDS = 8        # per project, for the generative projects
MAX_WIDTH = 1100            # px; figures are downscaled to keep the repo cloneable

# Metrics shown in the per-project table, in order of preference.
HEADLINE = ["test/accuracy", "test_accuracy", "test/f1", "test_f1", "best_val_acc",
            "val/accuracy", "val_acc", "val/f1", "final_fid", "fid", "metrics/mAP50(B)",
            "val_loss", "train_loss"]

JUNK_VALUE = re.compile(r'"_type"\s*:\s*"(histogram|table-file|image-file)"')


def clean(v):
    """Drop W&B media refs and histogram blobs; keep plain scalars and strings."""
    if v in ("", "None", "nan"):
        return ""
    if JUNK_VALUE.search(v) or len(v) > 200:
        return ""
    return v


def load_runs():
    rows = list(csv.DictReader((EXPORT / "all_runs_summary.csv").open()))
    by_project = {}
    for r in rows:
        by_project.setdefault(r["project"], []).append(r)
    return by_project


def load_projects():
    return {r["name"]: r for r in csv.DictReader((EXPORT / "projects_info.csv").open())}


def used_columns(runs, prefix):
    """Columns of this prefix that actually carry a value for this project."""
    cols = []
    for c in runs[0]:
        if not c.startswith(prefix):
            continue
        if any(clean(r[c]) for r in runs):
            cols.append(c)
    return sorted(cols)


def num(v):
    try:
        return float(v)
    except (TypeError, ValueError):
        return None


def headline_metric(runs):
    for name in HEADLINE:
        col = "metric/" + name
        if col in runs[0] and any(num(clean(r[col])) is not None for r in runs):
            return name, col
    return None, None


def write_runs_csv(path, runs):
    cfg = used_columns(runs, "config/")
    met = used_columns(runs, "metric/")
    base = ["run_name", "display_name", "state", "created_at", "compute_seconds",
            "tags", "wandb_url"]
    cols = base + cfg + met
    with path.open("w", newline="") as fh:
        w = csv.writer(fh)
        w.writerow(cols)
        for r in sorted(runs, key=lambda r: r["created_at"]):
            w.writerow([clean(r.get(c, "")) for c in cols])
    return len(cfg), len(met)


def copy_figures(project, runs, dest):
    """Copy evaluation figures for the most interesting runs, downscaled."""
    from PIL import Image

    if dest.exists():
        shutil.rmtree(dest)
    _, col = headline_metric(runs)
    if col:
        ranked = sorted(runs, key=lambda r: -(num(clean(r[col])) or -1e18))
    else:
        ranked = sorted(runs, key=lambda r: r["created_at"], reverse=True)

    copied, grids = 0, 0
    for r in ranked[:MAX_RUNS_WITH_FIGURES]:
        src = EXPORT / project / "runs" / f"{r['display_name']}_{r['run_name']}" / "images"
        if not src.is_dir():
            continue
        out = dest / r["display_name"]
        for img in sorted(src.glob("*.png")):
            is_eval = bool(EVAL.search(img.name))
            if not is_eval:
                if grids >= MAX_SAMPLE_GRIDS:
                    continue
                grids += 1
            out.mkdir(parents=True, exist_ok=True)
            # strip W&B's _step_hash suffix so filenames read cleanly
            name = re.sub(r"_\d+_[0-9a-f]{16,}(?=\.png$)", "", img.name)
            with Image.open(img) as im:
                if im.width > MAX_WIDTH:
                    h = round(im.height * MAX_WIDTH / im.width)
                    im = im.resize((MAX_WIDTH, h), Image.LANCZOS)
                im.convert("RGB" if im.mode in ("RGBA", "P", "LA") else im.mode)\
                  .save(out / name, optimize=True)
            copied += 1
    return copied


def project_readme(project, meta, runs, ncfg, nmet, nfig):
    name, col = headline_metric(runs)
    lines = [f"# {project}", ""]
    if meta:
        lines += [
            f"- **Runs logged**: {len(runs)}",
            f"- **Active**: {meta['createdAt'][:10]} to {(meta['lastActive'] or meta['updatedAt'])[:10]}",
            f"- **Compute**: {sum(num(r['compute_seconds']) or 0 for r in runs)/3600:.1f} GPU-hours logged",
            f"- **W&B project**: {meta['wandb_url']}",
            "",
        ]
    lines += [
        "## What is here",
        "",
        "| Path | Contents |",
        "| --- | --- |",
        f"| `runs.csv` | every run, {ncfg} hyperparameters and {nmet} metrics per row |",
        f"| `figures/` | {nfig} evaluation figures, one folder per run |",
        "| `code/` | training code for these runs |",
        "| `weights/` | final checkpoint and how to load it |",
        "",
    ]

    lines += ["## Runs", ""]
    header = "| Run | Date | " + (f"{name} | " if name else "") + "Runtime | W&B |"
    lines += [header, "| --- | --- | " + ("--- | " if name else "") + "--- | --- |"]
    ranked = sorted(runs, key=lambda r: r["created_at"])
    for r in ranked:
        val = ""
        if col:
            v = num(clean(r[col]))
            val = f"{v:.4g} | " if v is not None else "- | "
        mins = (num(r["compute_seconds"]) or 0) / 60
        lines.append(f"| {r['display_name']} | {r['created_at'][:10]} | {val}"
                     f"{mins:.0f} min | [link]({r['wandb_url']}) |")
    lines.append("")
    return "\n".join(lines)


ROOT_INTRO = """# Machine learning experiment log

Tahmidul Bin Ferdous, Department of Computer Science and Engineering,
International Islamic University Chittagong.

This repository is the working record behind my undergraduate research: {nruns} training
runs across {nproj} projects, logged to Weights & Biases between {first} and {last},
together with the code that produced them and the figures they generated.

Every run was trained on free-tier Kaggle accelerators (Tesla T4 or TPU v3-8), so
each project directory carries the notebook or script exactly as it ran there.

## How to read this

Each project directory contains:

| Path | Contents |
| --- | --- |
| `README.md` | what the project was for, and a table of every run with its headline metric |
| `runs.csv` | the full record: one row per run, every hyperparameter and every logged metric |
| `figures/` | evaluation figures, grouped by run |
| `code/` | the training code as it ran on Kaggle |
| `weights/` | the final checkpoint, or a link to it |

`runs.csv` is the primary evidence. It is exported directly from the Weights & Biases
API and is not edited by hand.

## Projects

"""

ROOT_OUTRO = """
## A note on the lung cancer work

The lung cancer projects study **data leakage in slice-level medical image splits**.
The IQ-OTH/NCCD dataset ships no patient identifier, so the honest comparison here is
between a random shuffle of slices and a split that respects file order. It is an
**ordering split**, not a patient-level split, and the difference matters: with a
random shuffle, slices from the same scan land on both sides of the split and the
reported accuracy is inflated. Holding the split ratio and the architecture fixed
across three seeds, moving from the shuffled split to the ordered split costs about
**7.5 percentage points** of accuracy.

Earlier write-ups of this work described the ordered condition as patient-level and
quoted a larger gap. That was wrong on both counts, and the numbers above supersede it.

## Reproducing

The training code targets Kaggle paths (`/kaggle/input/...`) and Kaggle accelerators.
To rerun a project, upload its `code/` directory as a Kaggle notebook and attach the
dataset named in the notebook header.

## Contact

Tahmidul Bin Ferdous, C221065, turing.accessories@gmail.com
"""


def main():
    by_project = load_runs()
    meta = load_projects()
    PROJECTS.mkdir(parents=True, exist_ok=True)

    summary, total_runs = [], 0
    for project, m in sorted(meta.items(), key=lambda kv: kv[1]["createdAt"], reverse=True):
        runs = by_project.get(project, [])
        if not runs:
            continue
        d = PROJECTS / project
        d.mkdir(parents=True, exist_ok=True)
        ncfg, nmet = write_runs_csv(d / "runs.csv", runs)
        nfig = copy_figures(project, runs, d / "figures")
        (d / "README.md").write_text(project_readme(project, m, runs, ncfg, nmet, nfig))
        for sub, note in (("code", "Training code for this project goes here."),
                          ("weights", "Final checkpoint for this project goes here.")):
            p = d / sub
            p.mkdir(exist_ok=True)
            if not any(p.iterdir()):
                (p / "README.md").write_text(f"# {sub}\n\n{note}\n")
        total_runs += len(runs)
        summary.append((project, m, len(runs), nfig))
        print(f"{project:32s} {len(runs):3d} runs  {nfig:3d} figures")

    dates = sorted(r["created_at"][:7] for rs in by_project.values() for r in rs)
    body = [ROOT_INTRO.format(nruns=total_runs, nproj=len(summary),
                              first=dates[0], last=dates[-1])]
    body.append("| Project | Runs | Period | What it is |")
    body.append("| --- | --- | --- | --- |")
    for project, m, n, _ in summary:
        period = f"{m['createdAt'][:7]} to {(m['lastActive'] or m['updatedAt'])[:7]}"
        body.append(f"| [{project}](projects/{project}/) | {n} | {period} | "
                    f"{DESCRIPTIONS.get(project, '')} |")
    body.append(ROOT_OUTRO)
    (ROOT / "README.md").write_text("\n".join(body))
    print(f"\n{total_runs} runs across {len(summary)} projects -> {ROOT}")


DESCRIPTIONS = {
    "lung-base-bench": "Shuffled vs ordered split, matched ratios, three seeds. The corrected headline result.",
    "lung_effnet_reproduction": "EfficientNet B0-B4 under both split conditions.",
    "ccal_paper_reproduction": "Reimplementation of the CCAL dual-CNN attention model.",
    "base_ccal": "First CCAL implementation and hyperparameter search.",
    "vit_lung_reproduction": "ViT-B/16 under both split conditions.",
    "plos_one_lung_reproduction": "Four-block CNN from the PLOS ONE paper, both split conditions.",
    "ct-rectified-flow": "Rectified flow generative model for CT slice augmentation.",
    "ct-diffusion-augmentation": "DDPM for CT slice augmentation.",
    "DSMaT-LungCancer": "Depthwise state-space (Mamba) classifier on the lung CT dataset.",
    "BanglaGPT1": "Small GPT trained from scratch on Bengali text.",
    "WGAN-FACE": "Wasserstein GAN on face images.",
    "gan-bengali-digit-generation": "DCGAN and WGAN variants generating Bengali handwritten digits.",
    "Ultralytics": "YOLOv11 detection models for university ID card detection.",
    "uncategorized": "Early exploratory runs.",
}

if __name__ == "__main__":
    sys.exit(main())
