_wandb:
    value:
        cli_version: 0.25.0
        e:
            be9njbdwzx8odfn1qmagsirk1z6pwyfx:
                codePath: train_diffusion.py
                codePathLocal: train_diffusion.py
                cpu_count: 2
                cpu_count_logical: 4
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "8656922775552"
                        used: "7165072465920"
                email: <redacted>
                executable: /usr/bin/python3
                gpu: Tesla T4
                gpu_count: 2
                gpu_nvidia:
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-8b05bb50-8b82-553e-42c1-25098c347228
                    - architecture: Turing
                      cudaCores: 2560
                      memoryTotal: "16106127360"
                      name: Tesla T4
                      uuid: GPU-e661fcae-bf47-1399-3bf3-7abe12254494
                host: f7a6dfa81d8c
                memory:
                    total: "33662472192"
                os: Linux-6.6.113+-x86_64-with-glibc2.35
                program: /kaggle/working/train_diffusion.py
                python: CPython 3.12.12
                root: /kaggle/working
                startedAt: "2026-02-22T21:37:08.504092Z"
                writerId: be9njbdwzx8odfn1qmagsirk1z6pwyfx
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 80
                - 105
            "2":
                - 1
                - 5
                - 41
                - 49
                - 53
                - 80
                - 105
            "3":
                - 2
                - 13
                - 16
                - 61
                - 62
            "4": 3.12.12
            "5": 0.25.0
            "8":
                - 2
            "12": 0.25.0
            "13": linux-x86_64
batch_size_per_gpu:
    value: 24
convergence_loss:
    value: 0.02
ddp:
    value: true
effective_batch_size:
    value: 48
ema_decay:
    value: 0.9999
epochs:
    value: 3000
gpu:
    value: Tesla T4
img_size:
    value: 128
learning_rate:
    value: 0.0003
max_training_hours:
    value: 10
model:
    value: ConditionalUNet
num_gpus:
    value: 2
params:
    value: ~19M
patience:
    value: 80
precision:
    value: fp16
timesteps:
    value: 1000
torch_compile:
    value: true
